// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	Name  *string `json:"name"`
	Books []*Book `json:"books"`
}

type Book struct {
	Title  *string `json:"title"`
	Author *Author `json:"author"`
}
